### PR TITLE
Conn 183 -- change enum name 

### PR DESCRIPTION
**Pull request by pri17**
Hi Peyman, 
I got this error when trying to pass a change with a reason, think due to the enum name the same with the field name? 
image

And thanks to fix the schema for me before! 👍 
Please have a look, thank you!

### CODE REVIEW

**Comment by peyman-mohtashami** [comment]
> Hi Peyman, I got this error when trying to pass a change with a reason, think due to the enum name the same with the field name? image
> 
> And thanks to fix the schema for me before! 👍 Please have a look, thank you!

Hi Gwen,
I deployed this fix now. Could you please check it.
Thanks.

**Comment by pri17** [comment]
@peyman-mohtashami  Hi Peyman, thanks for deploying! However, still get the same error. Maybe I will remove the "null" as an optional, put NULL into enum values and set enum default as "NULL"?  How do you think?  
image

Btw, has the cordova-plugin-radar- passive has been updated recently? As recently the connect app not prompting the permission requests, just skip to the finish page.  The plugin not actually requiring the location, bluetooth etc. permissions?
image

**Review by peyman-mohtashami — COMMENTED** [review]
@pri17 Deployed. Can you check it?

**Comment by pri17** [comment]
> @pri17 Deployed. Can you check it?

Thank you, the updated schema no error now!

**Pull request merged**
